version: '3.1'
services:
  web:
    build: .
    command: bash -c "python3.6 -m venv venv && source venv/bin/activate && /bin/bash"
    volumes:
      - .:/usr/src/app
      #- D:\Informatik\Master\graphql-playground\complete-guide-to-building-a-graphql-api\GRAPHQL:/usr/src/app
    ports:
     - "8000:8000"
    tty: true